-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-06-06 20:58:20 WIB
--   site:      SQL Server 2012
--   type:      SQL Server 2012

-- Disesuaikan untuk PostgreSQL

CREATE TABLE Absensi
    (
     absensi_id VARCHAR(50) NOT NULL ,
     tanggal TIMESTAMP NOT NULL ,
     status VARCHAR(50) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL , -- Changed from User_user_id
     Jadwal_jadwal_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Absensi ADD CONSTRAINT Absensi_PK PRIMARY KEY (absensi_id);

CREATE TABLE Detail_Pengajar
    (
     Users_user_id VARCHAR (7) NOT NULL , -- Changed from User_user_id
     Kelas_Users_user_id VARCHAR (7) NOT NULL , -- Changed from Kelas_User_user_id
     Matpel_mapel_id VARCHAR(50) NOT NULL ,
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

CREATE TABLE Feedback
    (
     feedback_id VARCHAR(50) NOT NULL ,
     feedback VARCHAR(255) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL -- Changed from User_user_id
    );

ALTER TABLE Feedback ADD CONSTRAINT Feedback_PK PRIMARY KEY (feedback_id);

CREATE TABLE Jadwal
    (
     jadwal_id VARCHAR(50) NOT NULL ,
     hari VARCHAR(20) NOT NULL ,
     jam_mulai VARCHAR(10) NOT NULL ,
     jam_selsai VARCHAR(10) NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL , -- Changed from Kelas_User_user_id
     Matpel_mapel_id VARCHAR(50) NOT NULL ,
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Jadwal ADD CONSTRAINT Jadwal_PK PRIMARY KEY (jadwal_id);

CREATE TABLE Kelas
    (
     kelas_id VARCHAR(50) NOT NULL ,
     nama_kelas VARCHAR(100) NOT NULL ,
     keterangan VARCHAR(255) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL , -- Changed from User_user_id
     Semester_semester_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Kelas ADD CONSTRAINT Kelas_PK PRIMARY KEY (Users_user_id, kelas_id); -- Changed from User_user_id

CREATE TABLE Materi
    (
     materi_id VARCHAR(50) NOT NULL ,
     nama_materi VARCHAR(255) NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL , -- Changed from Kelas_User_user_id
     Matpel_mapel_id VARCHAR(50) NOT NULL ,
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Materi ADD CONSTRAINT Materi_PK PRIMARY KEY (materi_id);

CREATE TABLE Matpel
    (
     mapel_id VARCHAR(50) NOT NULL ,
     nama_mapel VARCHAR(100) NOT NULL ,
     category VARCHAR(50) NOT NULL
    );

ALTER TABLE Matpel ADD CONSTRAINT Matpel_PK PRIMARY KEY (mapel_id);

CREATE TABLE Nilai
    (
     nilai_id VARCHAR(50) NOT NULL ,
     nilai BIGINT NOT NULL ,
     jenis_nilai VARCHAR(50) NOT NULL ,
     Matpel_mapel_id VARCHAR(50) NOT NULL ,
     Rapor_rapor_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Nilai ADD CONSTRAINT Nilai_PK PRIMARY KEY (nilai_id);

CREATE TABLE Pengumuman
    (
     pengumuman_id VARCHAR(50) NOT NULL ,
     pengumuman VARCHAR(255) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL -- Changed from User_user_id
    );

ALTER TABLE Pengumuman ADD CONSTRAINT Pengumuman_PK PRIMARY KEY (pengumuman_id);

CREATE TABLE Rapor
    (
     rapor_id VARCHAR(50) NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL , -- Changed from User_user_id
     Semester_semester_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Rapor ADD CONSTRAINT Rapor_PK PRIMARY KEY (rapor_id);

CREATE TABLE Role
    (
     role_id VARCHAR(1) NOT NULL ,
     role_name VARCHAR(50) NOT NULL
    );

ALTER TABLE Role ADD CONSTRAINT Role_PK PRIMARY KEY (role_id);

CREATE TABLE Semester
    (
     semester_id VARCHAR(50) NOT NULL ,
     tahun_ajaran VARCHAR(20) NOT NULL ,
     semester VARCHAR(20) NOT NULL ,
     tahun TIMESTAMP NOT NULL
    );

ALTER TABLE Semester ADD CONSTRAINT Semester_PK PRIMARY KEY (semester_id);

CREATE TABLE Tugas
    (
     tugas_id VARCHAR(50) NOT NULL ,
     keterangan VARCHAR(255) NOT NULL ,
     deadline TIMESTAMP NOT NULL ,
     tanggal_direlease TIMESTAMP NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL , -- Changed from Kelas_User_user_id
     Matpel_mapel_id VARCHAR(50) NOT NULL ,
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Tugas ADD CONSTRAINT Tugas_PK PRIMARY KEY (tugas_id);

CREATE TABLE Ujian
    (
     ujian_id VARCHAR(50) NOT NULL ,
     jenis_ujian VARCHAR(50) NOT NULL ,
     tanggal TIMESTAMP NOT NULL ,
     Kelas_Users_user_id VARCHAR (7) NOT NULL , -- Changed from Kelas_User_user_id
     Matpel_mapel_id VARCHAR(50) NOT NULL ,
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Ujian ADD CONSTRAINT Ujian_PK PRIMARY KEY (ujian_id);

CREATE TABLE Users -- Renamed from "User" and removed quotes
    (
     user_id VARCHAR (7) NOT NULL ,
     username VARCHAR(100) NOT NULL ,
     password VARCHAR(100) NOT NULL ,
     NIS_NIP VARCHAR(50) NOT NULL ,
     nama VARCHAR(100) NOT NULL ,
     gender VARCHAR(10) NOT NULL ,
     alamat VARCHAR(255) NOT NULL ,
     email VARCHAR(100) NOT NULL ,
     nomer_hp VARCHAR(20) NOT NULL ,
     Role_role_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Users ADD CONSTRAINT Users_PK PRIMARY KEY (user_id); -- Changed from User_PK

CREATE TABLE User_Log
    (
     userlog_id VARCHAR(50) NOT NULL ,
     jenis VARCHAR(50) NOT NULL ,
     keterangan VARCHAR(255) NOT NULL ,
     waktu TIMESTAMP NOT NULL ,
     Users_user_id VARCHAR (7) NOT NULL -- Changed from User_user_id
    );

ALTER TABLE User_Log ADD CONSTRAINT User_Log_PK PRIMARY KEY (userlog_id);

ALTER TABLE Absensi
    ADD CONSTRAINT Absensi_Jadwal_FK FOREIGN KEY
    (
     Jadwal_jadwal_id
    )
    REFERENCES Jadwal
    (
     jadwal_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Absensi
    ADD CONSTRAINT Absensi_Users_FK FOREIGN KEY -- Changed from Absensi_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id, -- Changed from Kelas_User_user_id
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id , -- Changed from User_user_id
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Users_FK FOREIGN KEY -- Changed from Detail_Pengajar_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Feedback
    ADD CONSTRAINT Feedback_Users_FK FOREIGN KEY -- Changed from Feedback_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Jadwal
    ADD CONSTRAINT Jadwal_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id, -- Changed from Kelas_User_user_id
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id , -- Changed from User_user_id
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Jadwal
    ADD CONSTRAINT Jadwal_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Kelas
    ADD CONSTRAINT Kelas_Semester_FK FOREIGN KEY
    (
     Semester_semester_id
    )
    REFERENCES Semester
    (
     semester_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Kelas
    ADD CONSTRAINT Kelas_Users_FK FOREIGN KEY -- Changed from Kelas_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Materi
    ADD CONSTRAINT Materi_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id, -- Changed from Kelas_User_user_id
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id , -- Changed from User_user_id
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Materi
    ADD CONSTRAINT Materi_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Nilai
    ADD CONSTRAINT Nilai_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Nilai
    ADD CONSTRAINT Nilai_Rapor_FK FOREIGN KEY
    (
     Rapor_rapor_id
    )
    REFERENCES Rapor
    (
     rapor_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Pengumuman
    ADD CONSTRAINT Pengumuman_Users_FK FOREIGN KEY -- Changed from Pengumuman_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Rapor
    ADD CONSTRAINT Rapor_Semester_FK FOREIGN KEY
    (
     Semester_semester_id
    )
    REFERENCES Semester
    (
     semester_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Rapor
    ADD CONSTRAINT Rapor_Users_FK FOREIGN KEY -- Changed from Rapor_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Tugas
    ADD CONSTRAINT Tugas_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id, -- Changed from Kelas_User_user_id
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id , -- Changed from User_user_id
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Tugas
    ADD CONSTRAINT Tugas_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Ujian
    ADD CONSTRAINT Ujian_Kelas_FK FOREIGN KEY
    (
     Kelas_Users_user_id, -- Changed from Kelas_User_user_id
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     Users_user_id , -- Changed from User_user_id
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Ujian
    ADD CONSTRAINT Ujian_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE User_Log
    ADD CONSTRAINT User_Log_Users_FK FOREIGN KEY -- Changed from User_Log_User_FK
    (
     Users_user_id -- Changed from User_user_id
    )
    REFERENCES Users -- Changed from "User"
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Users -- Changed from "User"
    ADD CONSTRAINT Users_Role_FK FOREIGN KEY -- Changed from User_Role_FK
    (
     Role_role_id
    )
    REFERENCES Role
    (
     role_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;