-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-06-06 20:58:20 WIB
--   site:      SQL Server 2012
--   type:      SQL Server 2012

-- Disesuaikan untuk PostgreSQL

CREATE TABLE Absensi
    (
     absensi_id VARCHAR(50) NOT NULL , -- Menambahkan panjang, asumsi ID tidak terlalu panjang
     tanggal TIMESTAMP NOT NULL ,       -- Mengganti DATETIME menjadi TIMESTAMP
     status VARCHAR(50) NOT NULL ,     -- Menambahkan panjang
     User_user_id VARCHAR (7) NOT NULL ,
     Jadwal_jadwal_id VARCHAR(50) NOT NULL -- Menambahkan panjang
    );

ALTER TABLE Absensi ADD CONSTRAINT Absensi_PK PRIMARY KEY (absensi_id);
-- Menghapus CLUSTERED dan klausa WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON)

CREATE TABLE Detail_Pengajar
    (
     User_user_id VARCHAR (7) NOT NULL ,
     Kelas_User_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

CREATE TABLE Feedback
    (
     feedback_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     feedback VARCHAR(255) NOT NULL ,   -- Menambahkan panjang, asumsi feedback bisa panjang
     User_user_id VARCHAR (7) NOT NULL
    );

ALTER TABLE Feedback ADD CONSTRAINT Feedback_PK PRIMARY KEY (feedback_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Jadwal
    (
     jadwal_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     hari VARCHAR(20) NOT NULL ,      -- Menambahkan panjang, asumsi nama hari
     jam_mulai VARCHAR(10) NOT NULL , -- Menambahkan panjang, asumsi format jam (e.g., "08:00")
     jam_selsai VARCHAR(10) NOT NULL , -- Menambahkan panjang
     Kelas_User_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Jadwal ADD CONSTRAINT Jadwal_PK PRIMARY KEY (jadwal_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Kelas
    (
     kelas_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     nama_kelas VARCHAR(100) NOT NULL , -- Menambahkan panjang
     keterangan VARCHAR(255) NOT NULL , -- Menambahkan panjang
     User_user_id VARCHAR (7) NOT NULL ,
     Semester_semester_id VARCHAR(50) NOT NULL -- Menambahkan panjang
    );

ALTER TABLE Kelas ADD CONSTRAINT Kelas_PK PRIMARY KEY (User_user_id, kelas_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Materi
    (
     materi_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     nama_materi VARCHAR(255) NOT NULL , -- Menambahkan panjang
     Kelas_User_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Materi ADD CONSTRAINT Materi_PK PRIMARY KEY (materi_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Matpel
    (
     mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     nama_mapel VARCHAR(100) NOT NULL , -- Menambahkan panjang
     category VARCHAR(50) NOT NULL
    );

ALTER TABLE Matpel ADD CONSTRAINT Matpel_PK PRIMARY KEY (mapel_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Nilai
    (
     nilai_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     nilai BIGINT NOT NULL ,
     jenis_nilai VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Matpel_mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Rapor_rapor_id VARCHAR(50) NOT NULL -- Menambahkan panjang
    );

ALTER TABLE Nilai ADD CONSTRAINT Nilai_PK PRIMARY KEY (nilai_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Pengumuman
    (
     pengumuman_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     pengumuman VARCHAR(255) NOT NULL , -- Menambahkan panjang
     User_user_id VARCHAR (7) NOT NULL
    );

ALTER TABLE Pengumuman ADD CONSTRAINT Pengumuman_PK PRIMARY KEY (pengumuman_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Rapor
    (
     rapor_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     User_user_id VARCHAR (7) NOT NULL ,
     Semester_semester_id VARCHAR(50) NOT NULL -- Menambahkan panjang
    );

ALTER TABLE Rapor ADD CONSTRAINT Rapor_PK PRIMARY KEY (rapor_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Role
    (
     role_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     role_name VARCHAR(50) NOT NULL
    );

ALTER TABLE Role ADD CONSTRAINT Role_PK PRIMARY KEY (role_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Semester
    (
     semester_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     tahun_ajaran VARCHAR(20) NOT NULL , -- Menambahkan panjang (e.g., "2024/2025")
     semester VARCHAR(20) NOT NULL ,    -- Menambahkan panjang (e.g., "Ganjil", "Genap")
     tahun TIMESTAMP NOT NULL           -- Mengganti DATETIME menjadi TIMESTAMP
    );

ALTER TABLE Semester ADD CONSTRAINT Semester_PK PRIMARY KEY (semester_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Tugas
    (
     tugas_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     keterangan VARCHAR(255) NOT NULL , -- Menambahkan panjang
     deadline TIMESTAMP NOT NULL ,      -- Mengganti DATETIME menjadi TIMESTAMP
     tanggal_direlease TIMESTAMP NOT NULL , -- Mengganti DATETIME menjadi TIMESTAMP
     Kelas_User_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Tugas ADD CONSTRAINT Tugas_PK PRIMARY KEY (tugas_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE Ujian
    (
     ujian_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     jenis_ujian VARCHAR(50) NOT NULL , -- Menambahkan panjang
     tanggal TIMESTAMP NOT NULL ,       -- Mengganti DATETIME menjadi TIMESTAMP
     Kelas_User_user_id VARCHAR (7) NOT NULL ,
     Matpel_mapel_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     Kelas_kelas_id VARCHAR(50) NOT NULL
    );

ALTER TABLE Ujian ADD CONSTRAINT Ujian_PK PRIMARY KEY (ujian_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE "User"
    (
     user_id VARCHAR (7) NOT NULL ,
     username VARCHAR(100) NOT NULL , -- Menambahkan panjang
     password VARCHAR(100) NOT NULL , -- Menambahkan panjang
     NIS_NIP VARCHAR(50) NOT NULL ,   -- Menambahkan panjang
     nama VARCHAR(100) NOT NULL ,     -- Menambahkan panjang
     gender VARCHAR(10) NOT NULL ,    -- Menambahkan panjang (e.g., "Laki-laki", "Perempuan")
     alamat VARCHAR(255) NOT NULL ,   -- Menambahkan panjang
     email VARCHAR(100) NOT NULL ,    -- Menambahkan panjang
     nomer_hp VARCHAR(20) NOT NULL ,   -- Menambahkan panjang
     Role_role_id VARCHAR(50) NOT NULL -- Menambahkan panjang
    );

ALTER TABLE "User" ADD CONSTRAINT User_PK PRIMARY KEY (user_id);
-- Menghapus CLUSTERED dan klausa WITH

CREATE TABLE User_Log
    (
     userlog_id VARCHAR(50) NOT NULL , -- Menambahkan panjang
     jenis VARCHAR(50) NOT NULL ,     -- Menambahkan panjang
     keterangan VARCHAR(255) NOT NULL , -- Menambahkan panjang
     waktu TIMESTAMP NOT NULL ,         -- Mengganti VARCHAR menjadi TIMESTAMP (asumsi waktu adalah datetime)
     User_user_id VARCHAR (7) NOT NULL
    );

ALTER TABLE User_Log ADD CONSTRAINT User_Log_PK PRIMARY KEY (userlog_id);
-- Menghapus CLUSTERED dan klausa WITH

ALTER TABLE Absensi
    ADD CONSTRAINT Absensi_Jadwal_FK FOREIGN KEY
    (
     Jadwal_jadwal_id
    )
    REFERENCES Jadwal
    (
     jadwal_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Absensi
    ADD CONSTRAINT Absensi_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Kelas_FK FOREIGN KEY
    (
     Kelas_User_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     User_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Detail_Pengajar
    ADD CONSTRAINT Detail_Pengajar_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Feedback
    ADD CONSTRAINT Feedback_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Jadwal
    ADD CONSTRAINT Jadwal_Kelas_FK FOREIGN KEY
    (
     Kelas_User_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     User_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Jadwal
    ADD CONSTRAINT Jadwal_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Kelas
    ADD CONSTRAINT Kelas_Semester_FK FOREIGN KEY
    (
     Semester_semester_id
    )
    REFERENCES Semester
    (
     semester_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Kelas
    ADD CONSTRAINT Kelas_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Materi
    ADD CONSTRAINT Materi_Kelas_FK FOREIGN KEY
    (
     Kelas_User_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     User_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Materi
    ADD CONSTRAINT Materi_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Nilai
    ADD CONSTRAINT Nilai_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Nilai
    ADD CONSTRAINT Nilai_Rapor_FK FOREIGN KEY
    (
     Rapor_rapor_id
    )
    REFERENCES Rapor
    (
     rapor_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Pengumuman
    ADD CONSTRAINT Pengumuman_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Rapor
    ADD CONSTRAINT Rapor_Semester_FK FOREIGN KEY
    (
     Semester_semester_id
    )
    REFERENCES Semester
    (
     semester_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Rapor
    ADD CONSTRAINT Rapor_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Tugas
    ADD CONSTRAINT Tugas_Kelas_FK FOREIGN KEY
    (
     Kelas_User_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     User_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Tugas
    ADD CONSTRAINT Tugas_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Ujian
    ADD CONSTRAINT Ujian_Kelas_FK FOREIGN KEY
    (
     Kelas_User_user_id,
     Kelas_kelas_id
    )
    REFERENCES Kelas
    (
     User_user_id ,
     kelas_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE Ujian
    ADD CONSTRAINT Ujian_Matpel_FK FOREIGN KEY
    (
     Matpel_mapel_id
    )
    REFERENCES Matpel
    (
     mapel_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE User_Log
    ADD CONSTRAINT User_Log_User_FK FOREIGN KEY
    (
     User_user_id
    )
    REFERENCES "User" -- Perbaikan pengutipan
    (
     user_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE "User"
    ADD CONSTRAINT User_Role_FK FOREIGN KEY
    (
     Role_role_id
    )
    REFERENCES Role
    (
     role_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;